### ISSUE TITLE
Circular dependency fix documentation

### ISSUE THREAD

**Issue by dnlsandiego** [paulelliott/fabrication#281]
I'm currently experiencing the same issue as https://github.com/paulelliott/fabrication/issues/269 with the circular dependency. I saw a PR was merged that fixed the issue but don't really see documentation anywhere that states how to utilize the fix for the issue. Is passing a block and purposefully nulling out the association the way to go? If so, are there any potential consequences/downsides for nulling out the association?

A snippet of my fabricators thats causing the error:
```ruby
Fabricator(:business) do
  name 'Birds'
  account_manager(fabricator: :user)
end

Fabricator(:user) do
  full_name 'Ross Geller'
  business
end
```

**Comment by paulelliott** [comment]
You are correct that it never made it into the documentation. I'm adding it this morning.

If you add an `inverse_of` to your `account_manager` field it should fix the problem for you.

```
Fabricator(:business) do
  name 'Birds'
  account_manager(fabricator: user, inverse_of: :business)
end
```

**Comment by dnlsandiego** [comment]
Awsome! Thanks for getting back so quickly. Really appreciate it. 

PS. 
Thanks for all your work! Really loving this gem over all the other factory solutions. Much cleaner and easy to work with.

**Comment by paulelliott** [comment]
Just updated the docs. Once the CDN updates it should be live.

Thanks! 😄

**Comment by dnlsandiego** [comment]
Thanks! Saw the updated docs and followed it but I'm still getting the same errors.

Here's the stack trace:

```
SystemStackError: stack level too deep
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabrication/schematic/definition.rb:100:in `initialize_copy'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabrication/schematic/definition.rb:112:in `initialize_clone'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabrication/schematic/definition.rb:112:in `clone'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabrication/schematic/definition.rb:112:in `merge'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabrication/schematic/definition.rb:77:in `fabricate'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabricate.rb:33:in `create'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabrication.rb:63:in `Fabricate'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabrication/generator/active_record.rb:33:in `block in build_default_expansion'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabrication/schematic/attribute.rb:40:in `instance_exec'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabrication/schematic/attribute.rb:40:in `execute'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabrication/schematic/attribute.rb:28:in `processed_value'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabrication/generator/base.rb:108:in `block in process_attributes'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabrication/generator/base.rb:107:in `each'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabrication/generator/base.rb:107:in `process_attributes'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabrication/generator/base.rb:6:in `build'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/fabrication-2.15.0/lib/fabrication/generator/base.rb:20:in `create'
... 9172 levels...
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.rc2/lib/active_support/dependencies.rb:287:in `load'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.rc2/lib/active_support/dependencies.rb:287:in `block in load'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.rc2/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.rc2/lib/active_support/dependencies.rb:287:in `load'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/commands/rails.rb:6:in `call'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/application.rb:191:in `block in serve'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/application.rb:161:in `fork'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/application.rb:161:in `serve'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
	from /Users/dnlsandiego/.rvm/gems/ruby-2.2.4/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/dnlsandiego/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/dnlsandiego/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

Currently using version `2.15.2` of Fabrication and version `5.0.0.rc2` of Rails 

Fabricators: 

```ruby
Fabricator(:business) do
  name 'Central Perk'
  domain_name 'central-perk'
  business_type 'Coffee Shop'

  account_manager(fabricator: :user, inverse_of: :business)
end

Fabricator(:user) do
  name 'Gunther'
  email 'gunther@testing2.com'
  password 'testing12345678'

  business(inverse_of: :user) # Tried it without the `inverse_of: :user` but still throws error
end
```

There's probably something simple I'm missing here...

**Comment by paulelliott** [comment]
I think `business` should have `inverse_of: :account_manager`.

**Comment by dnlsandiego** [comment]
Just tried that and still having the same errors.

**Comment by paulelliott** [comment]
What is the nature of the relationships between those models?

**Comment by dnlsandiego** [comment]
They are currently set up as:

```ruby
class Business < ApplicationRecord
  has_one :account_manager, class_name: 'User', foreign_key: 'account_manager_id', dependent: :destroy
  ...
end
```
```ruby
class User < ApplicationRecord
  belongs_to :business, foreign_key: 'account_manager_id'
  ...
end
```

**Comment by paulelliott** [comment]
Can you try manually breaking the cycle by specifying the fabricator on one of the classes like so?

```
Fabricator(:business) do
  name 'Central Perk'
  domain_name 'central-perk'
  business_type 'Coffee Shop'

  account_manager { Fabricate.build(:user, business: nil) }
end
```

**Comment by dnlsandiego** [comment]
Yes, that does work. But doesn't the inverse_of arg take of care that internally?

**Comment by paulelliott** [comment]
Yes, your effectively doing the same thing as `inverse_of` now.

Any chance you'd want to take a crack at writing a failing test that demonstrates this?

**Comment by dnlsandiego** [comment]
Sure. But I'm still pretty new to ruby and testing overall, so might take longer for me to take a crack at it.

**Comment by mallowigi** [comment]
Hijacking this thread.

From the documenation, something as simple as 
```
Fabricator(:person) do
  vehicle
end
```
should be working out of the box. However it's not, as I'm getting an `xxx must exist`.

I have the same problem as OP, and it is weird that i have to use build for such a simple case.
